name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build devcontainer
      run: make devcontainer

    - name: Run CI
      run: make devcontainer-ci
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_STATE_ENCRYPTION_KEY: ${{ secrets.TF_STATE_ENCRYPTION_KEY }}